### ISSUE TITLE
ECHR-OD Explorer crash

### ISSUE THREAD

**Issue by ewinge** [echr-od/ECHR-OD_explorer#14]
Hi

I get internal server errors when I try to open any case, such as:

https://echr-opendata.eu/cases/001-206516
https://echr-opendata.eu/cases/001-206512
https://echr-opendata.eu/cases/001-206519

The error is " OperationalError: no such table: table".

**Comment by aquemy** [comment]
Hi, thanks for the report.

Yes, the problem comes from the fact the database schema changed, the explorer has been adapted to the new schema.
But... as the server to generate the database does not have enouhg memory, it has 50% chances to crash during the build, which is what happened.

I need to regenerate the build manually and incrementally. Should take a couple of days.

**Comment by aquemy** [comment]
The explorer is back.
I unfortunately had to shut it down to be have enough RAM to regenerate the SQL database.

**Comment by ewinge** [comment]
Thanks :)

It seems the data structure is different between the API and the data set for download:
https://echr-opendata.eu/download/2.0.0/unstructured/cases/json
Does this have anything to do with the database schema change that you mentioned?

**Comment by aquemy** [comment]
@ewinge that is correct. The server is only capable of regenerating the database but not the datasets that requires the NLP models (i.e. over 20GB RAM).
I'll regenerate them this week-end as well.
