### ISSUE TITLE
Download links give 500 Server Error

### ISSUE THREAD

**Issue by ewinge** [echr-od/ECHR-OD_explorer#15]
Hi

The links to the data sets on this page give error messages:
https://echr-opendata.eu/download/

For example, these links don't work:
https://echr-opendata.eu/download/2.0.0/structured/cases/csv
https://echr-opendata.eu/download/2.0.0/structured/cases/json

**Comment by aquemy** [comment]
Yes - this is exactly due to the same problem as before.
Before we got far many cases than initially, generating the flat cases becomes extremely challenging given the limited environment.

I think I will temporarily deactivate the flat case generation the time I either find a better environment or a smarter way of doing it.
